<?php 
define("ABS", __DIR__);
define("LANGUAGES", "en");
define("DB_HOST", "127.0.0.1");
define("DB_LOGIN", "msv");
define("DB_PASSWORD", "");
define("DB_NAME", "msv");
define("DB_REQUIRED", true);
define("DATE_FORMAT", "d.m.Y H:i:s");
define("PROTOCOL", "http://");
define("MASTERHOST", "");
define("UPLOAD_FILES_PATH", __DIR__."/content");
define("CONTENT_URL", "/content");
define("PHP_HIDE_ERRORS", true);
define("DEBUG", false);
define("DEBUG_LOG", "");
define("SITE_CLOSED", false);
define("SHOW_ADMIN_MENU", 1);
define("PHP_LOCALE", "en_US.UTF-8");
define("PHP_TIMEZONE", "Europe/Berlin");
define("DATABASE_ENCODING", "utf8");
define("JS_BEFORE_BODY", false);
define("SUBDOMAIN_LANGUAGES", false);
define("REP", "http://rep.msvhost.com/api/rep/main/");
define("USER_HASH_PASSWORD", true);
define("USER_IGNORE_PRIVILEGES", false);
define("SMARTY_DIR", __DIR__."/include/custom/smarty/");
define("ADMIN_URL", "/admin/");
