<?php 
define("ABS", "H:\OpenServer\domains\sitegraph.ua\src");
define("LANGUAGES", "ru,ua");
define("DB_HOST", "localhost");
define("DB_LOGIN", "mysql");
define("DB_PASSWORD", "mysql");
define("DB_NAME", "sitograph");
define("DB_REQUIRED", false);
define("DATE_FORMAT", "d.m.Y H:i:s");
define("PROTOCOL", "http://");
define("MASTERHOST", "");
define("UPLOAD_FILES_PATH", "H:\OpenServer\domains\sitegraph.ua\src/content");
define("CONTENT_URL", "/content");
define("PHP_HIDE_ERRORS", false);
define("DEBUG", true);
define("DEBUG_LOG", "/var/log/msv-debug.log");
define("SITE_CLOSED", false);
define("SHOW_ADMIN_MENU", 1);
define("PHP_LOCALE", "en_US.UTF-8");
define("PHP_TIMEZONE", "Europe/Kiev");
define("DATABATE_ENCODING", "utf8");
define("FORSE_TRAILING_SLASH", true);
define("SUBDOMAIN_LANGUAGES", false);
define("REP", "http://rep.msvhost.com/rep/main/");
define("USER_HASH_PASSWORD", true);
define("USER_IGNORE_PRIVILEGES", false);
