<?php
// *** ./index.php
// *** DO NOT EDIT THIS FILE
// *** WILL BE OVERWRITTEN DURING UPDATE

include("config.php");
include("load.php");



MSV_Start();


// MODULES
MSV_Load();




MSV_Output();






